name: Maven CI/CD

on:
 push:
    branches: [ main, feature/meta-model-view ]
 pull_request:
    branches: [ main, feature/meta-model-view ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11


    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build project with Maven
      run: mvn clean install

    - name: Create assembly
      run: mvn -f fabric-server-pe/pom.xml assembly:single

    - name: Archive assembly
      uses: actions/upload-artifact@v3
      with:
        name: assembly
        path: fabric-server-pe/target/fabric-server-pe-*.zip
